-- 创建相册城市表
CREATE TABLE IF NOT EXISTS `album_city` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `city` VARCHAR(100) NOT NULL COMMENT '城市名称',
  `count` INT NOT NULL DEFAULT 0 COMMENT '该城市的图片数量',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_city` (`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='相册城市统计表';
